version: '3'
services:
  wendy:
    build: .
    env_file: .env
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "dist/healthcheck.js"]
      interval: 60s
      timeout: 10s
      retries: 3 